#Independent settings for the planner's costmap
#
# This costmap is not used currently, it is ignored by
# sbpl_lattice_planner_3d.cpp unless someone calls
# useMultiLayer( false ).  (But they don't, they call it with true.)
#
global_costmap: 
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 2.0
  publish_frequency: 0.5
  static_map: true
  rolling_window: false
